Attribute VB_Name = "modGlobal"
Option Explicit
'Property Variables:
Public m_Max As Integer
Public m_Min As Integer
Public m_AngleMax As Integer
Public m_AngleMin As Integer
Public m_IntSmall As Integer
Public m_IntBig As Integer
Public m_NeedleStyle As Integer
Public m_NeedleSize As Integer
Public m_NeedleColor As OLE_COLOR
Public m_NeedleMovement As Integer
Public m_TickSmallColor As OLE_COLOR
Public m_TickBigColor As OLE_COLOR
Public m_BorderColor As OLE_COLOR
Public m_BorderThickness As Integer
Public m_BackColor As OLE_COLOR
Public m_TextLabel As String
Public m_TextFont As Font
Public m_ValueLabel As String
Public m_ValueFont As Font
Public m_ValueColor As OLE_COLOR
Public m_TextColor As OLE_COLOR
Public m_ScaleFont As Font
Public m_ScaleInterval As Integer
Public m_Value As Variant
Public TextY As Currency
Public ValueY As Currency
Public m_Size As Integer
Public NeedleRef As Integer
